# Code Generated by Sidekick is for learning and experimentation purposes only.
.PHONY: setup analyze eval mcp-serve clean

setup:
	uv pip install -r requirements.txt
	python -m spacy download en_core_web_sm
	@echo "Setup complete. Verify with: python -c 'from sklearn.cluster import HDBSCAN; print(\"OK\")'"

analyze:
	jupyter notebook notebooks/analysis.ipynb

eval:
	python evals/run_eval.py

mcp-serve:
	python mcp_server/server.py

clean:
	find . -type d -name "__pycache__" -exec rm -rf {} +
	find . -type d -name ".ipynb_checkpoints" -exec rm -rf {} +
