"""Pydantic schemas — single source of truth for all data shapes."""
from ti.schema.transcript import (
    Meeting,
    Speaker,
    SpeakerTurn,
    Utterance,
    JoinLeaveEvent,
    KeyMoment,
    PreTaggedSummary,
    TranscriptDoc,
)
from ti.schema.enrichment import (
    CallType,
    Topic,
    Entity,
    SpeakerSentiment,
    EntitySentiment,
    SentimentArc,
    RiskSignal,
    StructuredActionItem,
    EnrichmentResult,
)
from ti.schema.insight import (
    Citation,
    CustomerJourneyNode,
    TrustTrajectoryComponents,
    CustomerJourney,
    ActionItemStatus,
    ActionLineageRecord,
    OwnerLineageSummary,
    Insight,
)

__all__ = [
    "Meeting",
    "Speaker",
    "SpeakerTurn",
    "Utterance",
    "JoinLeaveEvent",
    "KeyMoment",
    "PreTaggedSummary",
    "TranscriptDoc",
    "CallType",
    "Topic",
    "Entity",
    "SpeakerSentiment",
    "EntitySentiment",
    "SentimentArc",
    "RiskSignal",
    "StructuredActionItem",
    "EnrichmentResult",
    "Citation",
    "CustomerJourneyNode",
    "TrustTrajectoryComponents",
    "CustomerJourney",
    "ActionItemStatus",
    "ActionLineageRecord",
    "OwnerLineageSummary",
    "Insight",
]
